//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taixevaxe
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string MaHoaDon { get; set; }
        public string ThoiGian { get; set; }
        public string NgXuatHD { get; set; }
        public string MaSoVe { get; set; }
        public string SoTien { get; set; }
    
        public virtual Ve Ve { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
