//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taixevaxe
{
    using System;
    using System.Collections.Generic;
    
    public partial class LenhXuatBen
    {
        public string Malxb { get; set; }
        public string TrangThai { get; set; }
        public Nullable<System.DateTime> GioRa { get; set; }
        public Nullable<System.DateTime> GioVao { get; set; }
    
        public virtual XE XE { get; set; }
    }
}
