//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taixevaxe
{
    using System;
    using System.Collections.Generic;
    
    public partial class XE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XE()
        {
            this.PhieuDangTais = new HashSet<PhieuDangTai>();
            this.Ves = new HashSet<Ve>();
        }
    
        public string MaXe { get; set; }
        public string BienSo { get; set; }
        public string HieuXe { get; set; }
        public int LoaiXe { get; set; }
        public string ChuXe { get; set; }
        public string ChatLuong { get; set; }
        public string TrangThaiHoatDong { get; set; }
        public string TaiXeChinh { get; set; }
    
        public virtual ChatLuong ChatLuong1 { get; set; }
        public virtual ChuXe ChuXe1 { get; set; }
        public virtual LenhXuatBen LenhXuatBen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuDangTai> PhieuDangTais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve> Ves { get; set; }
    }
}
